
#define NUMBER_OF_FLAVOR_TEXTS 19
const char flavorTexts[NUMBER_OF_FLAVOR_TEXTS][21] = {
  "This was a triumph",
  "So time, much cyborg",
  //"Suck it, Trebek",
  //"Danger Will Robinson",
  "Exterminate!",
  "Hack the planet!",
  //"How may I serve you?",
  "Zack was here",
  //"Voidstar Lab ftw",
  //"#swag",
  "Resistance is futile",
  //"UUDDLRLRBASelStart",
  //"Fire systm activated",
  "Robot initiation",
  //"Heaven or hell!",
  //"Scotch scotch scotch",
  //"We are the dreamers",
  //"Wanna hold my moose?",
  "\"ok glass\"",
  //"Daisy, Daisy...",
  //"We want your soul",
  //"Bewbs",
  //"Spaaaaaaaace!",
  "To infinity & beyond",
  "Haiiii-yah!",
  "HP: 325 Rads: 150",
  //"Memento mori",
  //"Howdy, meatsack!",
  //"01001000 01101001",
  //"Don't make me think",
  "Don't panic",
  "Get to the chopper!",
  "Go go gadget watch",
  "Sorry, I'm on duty",
  "It's morphin' time!",
  "Right away, Zack",
  "I'm on my way",
  "It's so bad"
  //"Optigon, lol"
 //XXXXXXXXXXXXXXXXXXXX
};
